[package]
name = "rust_server"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
mongodb = "2.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jsonwebtoken = "8.0"
bcrypt = "0.13"
futures = "0.3"
chrono = "0.4"